language: java
jdk:
- openjdk8

# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "mbouchenoire-github"
script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- mvn clean test -Pcoverage jacoco:report coveralls:report